=== syndesisio/syndesis/app/connector/support/maven-plugin/src/main/resources/connector-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "actions": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "actionType": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "descriptor": {
              "type": "object",
              "properties": {
                "componentScheme": {
                  "type": "string"
                },
                "configuredProperties": {
                  "type": "object"
                },
                "connectorFactory": {
                  "type": "string"
                },
                "connectorCustomizers": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ],
                  "additionalProperties": false
                },
                "exceptionHandler": {
                  "type": "string"
                },
                "inputDataShape": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind"
                  ],
                  "additionalProperties": false
                },
                "outputDataShape": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind"
                  ],
                  "additionalProperties": false
                },
                "propertyDefinitionSteps": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "description": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "properties": {
                          "type": "object"
                        }
                      },
                      "required": [
                        "description",
                        "name",
                        "properties"
                      ],
                      "additionalProperties": false
                    }
                  ]
                },
                "standardizedErrors": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "displayName": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "displayName"
                      ],
                      "additionalProperties": false
                    }
                  ]
                }
              },
              "required": [
                "inputDataShape",
                "outputDataShape"
              ],
              "additionalProperties": false
            },
            "id": {
              "type": "string"
            },
            "metadata": {
              "type": "object"
            },
            "name": {
              "type": "string"
            },
            "pattern": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "actionType",
            "description",
            "descriptor",
            "id",
            "name",
            "pattern"
          ],
          "additionalProperties": false
        }
      ]
    },
    "componentScheme": {
      "type": "string"
    },
    "configuredProperties": {
      "type": "object"
    },
    "connectorCustomizers": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "connectorFactory": {
      "type": "string"
    },
    "dependencies": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "type"
          ],
          "additionalProperties": false
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "properties": {
      "type": "object"
    },
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "actions",
    "description",
    "icon",
    "id",
    "name"
  ],
  "additionalProperties": false
}

=== syndesisio/syndesis/app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
{
  "actions": [
    {
      "actionType": "connector",
      "description": "Send a message to specific Slack user.",
      "descriptor": {
        "configuredProperties": {},
        "connectorCustomizers": [
          "io.syndesis.connector.slack.SlackChannelCustomizer"
        ],
        "inputDataShape": {
          "kind": "java",
          "type": "io.syndesis.connector.slack.SlackPlainMessage"
        },
        "outputDataShape": {
          "kind": "none"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Send a message to a specific Slack user.",
            "name": "User Name",
            "properties": {
              "receiver": {
                "deprecated": false,
                "displayName": "Username",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "labelHint": "The name of the Slack user to send the message to.",
                "required": true,
                "secret": false,
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:slack-username-connector",
      "name": "User Name",
      "pattern": "To"
    },
    {
      "actionType": "connector",
      "description": "Send a message to a specific Slack channel.",
      "descriptor": {
        "configuredProperties": {},
        "connectorCustomizers": [
          "io.syndesis.connector.slack.SlackChannelCustomizer"
        ],
        "inputDataShape": {
          "kind": "java",
          "type": "io.syndesis.connector.slack.SlackPlainMessage"
        },
        "outputDataShape": {
          "kind": "none"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Send a message to a specific Slack channel.",
            "name": "Channel",
            "properties": {
              "channel": {
                "deprecated": false,
                "displayName": "Channel",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "labelHint": "The name of the Slack channel to send the message to.",
                "required": true,
                "secret": false,
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:slack-channel-connector",
      "name": "Channel",
      "pattern": "To",
      "tags": [
        "dynamic"
      ]
    },
    {
      "actionType": "connector",
      "description": "Read Messages from a specific channel",
      "descriptor": {
        "configuredProperties": {},
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "java",
          "type": "org.apache.camel.component.slack.helper.SlackMessage"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Consume messages from a specific channel",
            "name": "Channel",
            "properties": {
              "channel": {
                "deprecated": false,
                "displayName": "Channel",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "labelHint": "The channel from where you want to consume",
                "order": "1",
                "required": true,
                "secret": false,
                "type": "string"
              },
              "delay": {
                "defaultValue": 500,
                "deprecated": false,
                "displayName": "Delay",
                "group": "scheduler",
                "javaType": "long",
                "kind": "parameter",
                "label": "consumer,scheduler",
                "labelHint": "Milliseconds before the next poll. You can also specify time values using units such as 60s (60 seconds) 5m30s (5 minutes and 30 seconds) and 1h (1 hour).",
                "optionalPrefix": "consumer.",
                "order": "2",
                "required": false,
                "secret": false,
                "type": "duration"
              },
              "maxResults": {
                "defaultValue": "10",
                "deprecated": false,
                "displayName": "Maximum Messages to Retrieve",
                "group": "consumer",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "label": "consumer",
                "labelHint": "Gets the maximum number of messages as a limit to poll at each polling. Is default unlimited but use 0 or negative number to disable it as unlimited.",
                "order": "3",
                "required": false,
                "secret": false,
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:slack-channel-consumer-connector",
      "name": "Read Messages",
      "pattern": "From",
      "tags": [
        "dynamic"
      ]
    }
  ],
  "componentScheme": "slack",
  "configuredProperties": {},
  "dependencies": [
    {
      "id": "@project.groupId@:@project.artifactId@:@project.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Obtain and send messages.",
  "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjEuOTQyIiBoZWlnaHQ9IjEyMS44NDIiPjxwYXRoIGQ9Ik03OS4wMyA3LjUxMWMtMS45LTUuNy04LTguOC0xMy43LTctNS43IDEuOS04LjggOC03IDEzLjdsMjguMSA4Ni40YzEuOSA1LjMgNy43IDguMyAxMy4yIDYuNyA1LjgtMS43IDkuMy03LjggNy40LTEzLjQgMC0uMi0yOC04Ni40LTI4LTg2LjR6IiBmaWxsPSIjZWNiMzJkIi8+PHBhdGggZD0iTTM1LjUzIDIxLjYxMWMtMS45LTUuNy04LTguOC0xMy43LTctNS43IDEuOS04LjggOC03IDEzLjdsMjguMSA4Ni40YzEuOSA1LjMgNy43IDguMyAxMy4yIDYuNyA1LjgtMS43IDkuMy03LjggNy40LTEzLjQgMC0uMi0yOC04Ni40LTI4LTg2LjR6IiBmaWxsPSIjNjNjMWEwIi8+PHBhdGggZD0iTTExNC40MyA3OS4wMTFjNS43LTEuOSA4LjgtOCA3LTEzLjctMS45LTUuNy04LTguOC0xMy43LTdsLTg2LjUgMjguMmMtNS4zIDEuOS04LjMgNy43LTYuNyAxMy4yIDEuNyA1LjggNy44IDkuMyAxMy40IDcuNC4yIDAgODYuNS0yOC4xIDg2LjUtMjguMXoiIGZpbGw9IiNlMDFhNTkiLz48cGF0aCBkPSJNMzkuMjMgMTAzLjUxMWM1LjYtMS44IDEyLjktNC4yIDIwLjctNi43LTEuOC01LjYtNC4yLTEyLjktNi43LTIwLjdsLTIwLjcgNi43eiIgZmlsbD0iIzMzMTQzMyIvPjxwYXRoIGQ9Ik04Mi44MyA4OS4zMTFjNy44LTIuNSAxNS4xLTQuOSAyMC43LTYuNy0xLjgtNS42LTQuMi0xMi45LTYuNy0yMC43bC0yMC43IDYuN3oiIGZpbGw9IiNkNjIwMjciLz48cGF0aCBkPSJNMTAwLjIzIDM1LjUxMWM1LjctMS45IDguOC04IDctMTMuNy0xLjktNS43LTgtOC44LTEzLjctN2wtODYuNCAyOC4xYy01LjMgMS45LTguMyA3LjctNi43IDEzLjIgMS43IDUuOCA3LjggOS4zIDEzLjQgNy40LjIgMCA4Ni40LTI4IDg2LjQtMjh6IiBmaWxsPSIjODlkM2RmIi8+PHBhdGggZD0iTTI1LjEzIDU5LjkxMWM1LjYtMS44IDEyLjktNC4yIDIwLjctNi43LTIuNS03LjgtNC45LTE1LjEtNi43LTIwLjdsLTIwLjcgNi43eiIgZmlsbD0iIzI1OGI3NCIvPjxwYXRoIGQ9Ik02OC42MyA0NS44MTFjNy44LTIuNSAxNS4xLTQuOSAyMC43LTYuNy0yLjUtNy44LTQuOS0xNS4xLTYuNy0yMC43bC0yMC43IDYuN3oiIGZpbGw9IiM4MTljM2MiLz48L3N2Zz4=",
  "id": "slack",
  "name": "Slack",
  "properties": {
    "iconEmoji": {
      "deprecated": false,
      "displayName": "Message Avatar Emoji",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "labelHint": "The Slack emoji that will be used for the message avatar.",
      "order": "4",
      "required": false,
      "secret": false,
      "type": "string"
    },
    "iconUrl": {
      "deprecated": false,
      "displayName": "Message Avatar Icon URL",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "labelHint": "The avatar that the connection will use when sending messages to a channel or user.",
      "order": "5",
      "required": false,
      "secret": false,
      "type": "string"
    },
    "token": {
      "deprecated": false,
      "displayName": "Token for Accessing Slack API",
      "group": "consumer",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "labelHint": "The token to use for obtaining messages from a Slack channel.",
      "order": "2",
      "raw": true,
      "required": true,
      "secret": true,
      "type": "string"
    },
    "username": {
      "deprecated": false,
      "displayName": "Sending User Name for Messages",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "labelHint": "The user name that the bot will have when sending messages to a channel or user.",
      "order": "3",
      "required": false,
      "secret": false,
      "type": "string"
    },
    "webhookUrl": {
      "deprecated": false,
      "displayName": "Slack Webhook URL",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "labelHint": "The webhook URL to send messages to.",
      "order": "1",
      "raw": true,
      "required": true,
      "secret": true,
      "type": "string"
    }
  },
  "tags": [
    "verifier"
  ]
}

=== syndesisio/syndesis/app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
{
  "actions": [
    {
      "actionType": "connector",
      "description": "Start a Syndesis integration from a provided API",
      "descriptor": {
        "componentScheme": "direct",
        "connectorCustomizers": [
          "io.syndesis.connector.apiprovider.ApiProviderStartEndpointCustomizer"
        ],
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "any"
        },
        "propertyDefinitionSteps": [
          {
            "description": "API Provider Configuration",
            "name": "configuration",
            "properties": {
              "name": {
                "componentProperty": false,
                "deprecated": false,
                "description": "The operation ID as defined in the API spec",
                "displayName": "Operation ID",
                "javaType": "String",
                "kind": "parameter",
                "required": true,
                "secret": false,
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:api-provider-start",
      "name": "Provided API",
      "pattern": "From",
      "tags": [
        "expose"
      ]
    },
    {
      "actionType": "connector",
      "description": "End action of Syndesis integrations that start from a provided API",
      "descriptor": {
        "componentScheme": "bean",
        "standardizedErrors": [
          {
            "name": "SERVER_ERROR",
            "displayName": "ServerError"
          }
        ],
        "configuredProperties": {
          "beanName": "io.syndesis.connector.apiprovider.NoOpBean",
          "method": "process"
        },
        "connectorCustomizers": [
          "io.syndesis.connector.apiprovider.ApiProviderReturnPathCustomizer"
        ],
        "exceptionHandler": "io.syndesis.connector.apiprovider.ApiProviderOnExceptionHandler",
        "inputDataShape": {
          "kind": "any"
        },
        "outputDataShape": {
          "kind": "none"
        },
        "propertyDefinitionSteps": [
          {
            "description": "API Provider Return Path Configuration",
            "name": "configuration",
            "properties": {
              "defaultResponse": {
                "order": 0,
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Default Response",
                "javaType": "String",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "legend"
              },
              "httpResponseCode": {
                "order": 1,
                "componentProperty": false,
                "deprecated": false,
                "description": "The return code to set in the HTTP response",
                "displayName": "Return Code",
                "javaType": "String",
                "kind": "parameter",
                "required": true,
                "secret": false,
                "type": "select"
              },
              "errorHandling": {
                "order": 2,
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Error Handling",
                "javaType": "String",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "legend"
              },
              "returnBody": {
                "order": 3,
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Include error message in the return body",
                "displayNameCheckBox": "Select return body preference",
                "javaType": "Boolean",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "boolean"
              },
              "errorResponseCodes": {
                "order": 4,
                "componentProperty": false,
                "deprecated": false,
                "defaultValue": "{}",
                "description": "The return code to set according to different error situations",
                "displayName": "Error Response Codes",
                "javaType": "Map",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "mapset"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:api-provider-end",
      "name": "Provided API Return Path",
      "pattern": "To"
    }
  ],
  "dependencies": [
    {
      "id": "@project.groupId@:@project.artifactId@:@project.version@",
      "type": "MAVEN"
    },
    {
      "id": "org.apache.camel:camel-swagger-java:@camel.version@",
      "type": "MAVEN"
    },
    {
      "id": "org.apache.camel.springboot:camel-servlet-starter:@camel.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Expose Restful APIs",
  "icon": "assets:api-provider.svg",
  "id": "api-provider",
  "metadata": {
    "hide-from-connection-pages": true
  },
  "name": "API Provider"
}

=== syndesisio/syndesis/app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
{
  "actions": [
    {
      "actionType": "connector",
      "description": "Specify an amount of time and its unit to periodically trigger integration execution. ",
      "descriptor": {
        "componentScheme": "timer",
        "configuredProperties": {
          "timerName": "syndesis-timer"
        },
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "none"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Period",
            "name": "Period",
            "properties": {
              "period": {
                "componentProperty": false,
                "defaultValue": 60000,
                "deprecated": false,
                "description": "Period",
                "displayName": "Period",
                "javaType": "long",
                "kind": "parameter",
                "labelHint": "Delay between each execution of the integration.",
                "required": true,
                "secret": false,
                "type": "duration"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:timer-action",
      "name": "Simple",
      "pattern": "From"
    },
    {
      "actionType": "connector",
      "description": "Specify a cron utility expression for a more complex integration execution schedule.",
      "descriptor": {
        "componentScheme": "quartz",
        "configuredProperties": {
          "triggerName": "syndesis-quartz"
        },
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "none"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Cron",
            "name": "cron",
            "properties": {
              "cron": {
                "componentProperty": false,
                "defaultValue": "0 0/1 * * * ?",
                "deprecated": false,
                "description": "A cron expression, for example the expression for every minute is 0 0/1 * * * ?",
                "displayName": "Cron Expression",
                "javaType": "string",
                "kind": "parameter",
                "labelHint": "Delay between scheduling (executing) the integration expressed as a cron expression",
                "required": true,
                "secret": false,
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:timer-chron",
      "name": "Cron",
      "pattern": "From"
    }
  ],
  "configuredProperties": {},
  "dependencies": [
    {
      "id": "@project.groupId@:@project.artifactId@:@project.version@",
      "type": "MAVEN"
    },
    {
      "id": "org.apache.camel:camel-quartz:@camel.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Trigger events based on an interval or a quartz expression",
  "icon": "assets:timer.svg",
  "id": "timer",
  "metadata": {
    "hide-from-connection-pages": true
  },
  "name": "Timer"
}
