=== syndesisio/syndesis/app/connector/support/maven-plugin/src/main/resources/connector-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "actions": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "actionType": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "descriptor": {
              "type": "object",
              "properties": {
                "componentScheme": {
                  "type": "string"
                },
                "configuredProperties": {
                  "type": "object"
                },
                "connectorFactory": {
                  "type": "string"
                },
                "connectorCustomizers": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ],
                  "additionalProperties": false
                },
                "exceptionHandler": {
                  "type": "string"
                },
                "inputDataShape": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind"
                  ],
                  "additionalProperties": false
                },
                "outputDataShape": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind"
                  ],
                  "additionalProperties": false
                },
                "propertyDefinitionSteps": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "description": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "properties": {
                          "type": "object"
                        }
                      },
                      "required": [
                        "description",
                        "name",
                        "properties"
                      ],
                      "additionalProperties": false
                    }
                  ]
                },
                "standardizedErrors": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "displayName": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "displayName"
                      ],
                      "additionalProperties": false
                    }
                  ]
                }
              },
              "required": [
                "inputDataShape",
                "outputDataShape"
              ],
              "additionalProperties": false
            },
            "id": {
              "type": "string"
            },
            "metadata": {
              "type": "object"
            },
            "name": {
              "type": "string"
            },
            "pattern": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "actionType",
            "description",
            "descriptor",
            "id",
            "name",
            "pattern"
          ],
          "additionalProperties": false
        }
      ]
    },
    "componentScheme": {
      "type": "string"
    },
    "configuredProperties": {
      "type": "object"
    },
    "connectorCustomizers": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "connectorFactory": {
      "type": "string"
    },
    "dependencies": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "type"
          ],
          "additionalProperties": false
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "properties": {
      "type": "object"
    },
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "actions",
    "description",
    "icon",
    "id",
    "name"
  ],
  "additionalProperties": false
}

=== syndesisio/syndesis/app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
{
  "actions": [
    {
      "actionType": "connector",
      "description": "Read a resource from the server",
      "descriptor": {
        "configuredProperties": {
          "apiName": "read"
        },
        "connectorFactory": "io.syndesis.connector.odata.component.ODataComponentFactory",
        "connectorCustomizers": [
          "io.syndesis.connector.odata.customizer.ODataStartCustomizer"
        ],
        "inputDataShape": {
          "kind": "any"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
        {
            "description": "Enhance the service url with a resource path",
            "name": "Resource Path and Query Options",
            "properties": {
              "methodName": {
                "deprecated": false,
                "displayName": "Resource Collection",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "labelHint": "The resource collection to be queried, eg. an <i><b>EntitySetName</b></i> or <i><b>EntityFunctionImportCall</b></i>",
                "order": "1",
                "required": true,
                "secret": false,
                "type": "string"
              },
              "keyPredicate": {
                "deprecated": false,
                "displayName": "Entity Key Predicate",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "labelHint": "Parameter to refine the collection to a single entity, eg. People(<i><b>UserName='Bob'</i></b>) or Categories(<i><b>1</b></i>)",
                "order": "2",
                "required": false,
                "secret": false,
                "type": "string"
              },
              "queryParams": {
                "deprecated": false,
                "displayName": "Query Options",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "parameter",
                "label": "consumer",
                "labelHint": "Enter the full query to be applied to the collection in OData query syntax.",
                "order": "3",
                "required": false,
                "secret": false,
                "type": "string"
              },
              "filterAlreadySeen": {
                "deprecated": false,
                "displayName": "Filter Old Results",
                "group": "common",
                "javaType": "java.lang.Boolean",
                "kind": "parameter",
                "label": "consumer",
                "labelHint": "While repeatedly polling the connection, filter out those results already communicated.",
                "order": "4",
                "required": false,
                "secret": false,
                "type": "boolean"
              },
              "initialDelay": {
                "defaultValue": 1000,
                "deprecated": false,
                "displayName": "Interval before polling starts",
                "group": "consumer",
                "javaType": "java.lang.Integer",
                "kind": "parameter",
                "label": "consumer,scheduler",
                "labelHint": "Wait amount of time before starting to poll",
                "optionalPrefix": "consumer.",
                "order": "5",
                "required": false,
                "secret": false,
                "type": "duration"
              },
              "delay": {
                "defaultValue": 30000,
                "deprecated": false,
                "displayName": "Delay",
                "group": "scheduler",
                "javaType": "long",
                "kind": "parameter",
                "label": "consumer,scheduler",
                "labelHint": "Milliseconds before the next poll. You can also specify time values using units such as 60s (60 seconds) 5m30s (5 minutes and 30 seconds) and 1h (1 hour).",
                "optionalPrefix": "consumer.",
                "order": "6",
                "required": false,
                "secret": false,
                "type": "duration"
              },
              "backoffIdleThreshold": {
                "defaultValue": 1,
                "deprecated": false,
                "displayName": "Backoff Idle Threshold",
                "group": "scheduler",
                "javaType": "int",
                "kind": "parameter",
                "label": "consumer,scheduler",
                "labelHint": "If no results are returned after (Backoff Threshold) times then polling will become idle for (Backoff Threshold * Backoff Multiplier) seconds",
                "optionalPrefix": "consumer.",
                "order": "7",
                "required": false,
                "secret": false,
                "type": "integer"
              },
              "backoffMultiplier": {
                "defaultValue": 1,
                "deprecated": false,
                "displayName": "Backoff Multiplier",
                "group": "scheduler",
                "javaType": "int",
                "kind": "parameter",
                "label": "consumer,scheduler",
                "labelHint": "If no results are returned after (Backoff Threshold) times then polling will become idle for (Backoff Threshold * Backoff Multiplier) seconds",
                "optionalPrefix": "consumer.",
                "order": "8",
                "required": false,
                "secret": false,
                "type": "integer"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:odata-read-connector",
      "name": "Read",
      "pattern": "From",
      "tags": [
        "dynamic"
      ]
    }
  ],
  "componentScheme": "olingo4",
  "configuredProperties": {},
  "dependencies": [
    {
      "id": "@project.groupId@:@project.artifactId@:@project.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Communicate with an OData service",
  "icon": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDMwMCAzMDAiPgogIDxnIGlkPSJsYXllcjEiPgogICAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjMwMCIgaGVpZ2h0PSIzMDAiIGZpbGw9IiNmZThiMDAiIC8+CgogICAgPHJlY3QgeD0iMjYiIHk9IjMwIiB3aWR0aD0iMTExIiBoZWlnaHQ9IjI4IiBmaWxsPSJ3aGl0ZSIgLz4KICAgIDxyZWN0IHg9IjI2IiB5PSI4NiIgd2lkdGg9IjExMSIgaGVpZ2h0PSIyOCIgZmlsbD0id2hpdGUiIC8+CiAgICA8cmVjdCB4PSIyNiIgeT0iMTQyIiB3aWR0aD0iMTExIiBoZWlnaHQ9IjI4IiBmaWxsPSJ3aGl0ZSIgLz4KICAgIDxjaXJjbGUgY3g9IjgxLjUiIGN5PSIyMzAiIHI9IjQ4IiBmaWxsPSJ3aGl0ZSIgLz4KCiAgICA8cmVjdCB4PSIxNjMiIHk9IjMwIiB3aWR0aD0iMTExIiBoZWlnaHQ9IjI4IiBmaWxsPSJ3aGl0ZSIgLz4KICAgIDxyZWN0IHg9IjE2MyIgeT0iODYiIHdpZHRoPSIxMTEiIGhlaWdodD0iMjgiIGZpbGw9IndoaXRlIiAvPgogICAgPHJlY3QgeD0iMTYzIiB5PSIxNDIiIHdpZHRoPSIxMTEiIGhlaWdodD0iMjgiIGZpbGw9IndoaXRlIiAvPgogICAgPHJlY3QgeD0iMTYzIiB5PSIxOTgiIHdpZHRoPSIxMTEiIGhlaWdodD0iMjgiIGZpbGw9IndoaXRlIiAvPgogICAgCiAgPC9nPgo8L3N2Zz4K",
  "id": "odata",
  "name": "OData",
  "properties": {
    "serviceUri": {
      "deprecated": false,
      "displayName": "Service Root URL",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "labelHint": "The service root URL of your OData server",
      "order": "1",
      "required": true,
      "secret": false,
      "type": "string"
    },
      "basicUserName": {
      "componentProperty": true,
      "deprecated": false,
      "displayName": "User Name",
      "group": "security",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "label": "common,security",
      "labelHint": "Specify a user name for basic authentication of the odata service url, if required.",
      "order": "2",
      "required": false,
      "secret": false,
      "type": "string"
    },
    "basicPassword": {
      "componentProperty": true,
      "deprecated": false,
      "displayName": "Password",
      "group": "security",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "label": "common,security",
      "labelHint": "Specify a password for basic authentication of the odata service url, if required.",
      "order": "3",
      "required": false,
      "secret": true,
      "type": "string"
    },
    "skipCertificateCheck": {
      "componentProperty": true,
      "defaultValue": "false",
      "deprecated": false,
      "displayName": "Check Certificate",
      "enum": [
        {
          "label": "Disable",
          "value": "true"
        },
        {
          "label": "Enable",
          "value": "false"
        }
      ],
      "group": "security",
      "javaType": "java.lang.String",
      "kind": "property",
      "label": "common,security",
      "labelHint": "Ensure certificate checks are enabled for secure production environments. Disable for convenience in only development environments.",
      "order": "4",
      "required": false,
      "secret": false,
      "type": "string"
    },
    "clientCertificate": {
      "componentProperty": true,
      "deprecated": false,
      "description": "Client certificate for SSL connections",
      "displayName": "Client Certificate",
      "group": "security",
      "javaType": "java.lang.String",
      "kind": "parameter",
      "label": "common,security",
      "order": "5",
      "relation": [
        {
          "action": "ENABLE",
          "when": [
            {
              "id": "skipCertificateCheck",
              "value": "false"
            }
          ]
        }
      ],
      "required": false,
      "secret": false,
      "type": "textarea"
    }
  },
  "tags": [
    "verifier"
  ]
}

=== syndesisio/syndesis/app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
{
  "actions": [
    {
      "actionType": "connector",
      "description": "Publish data to the Kafka topic that you select.",
      "descriptor": {
        "configuredProperties": {},
        "inputDataShape": {
          "kind": "any"
        },
        "outputDataShape": {
          "kind": "none"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Specify Kafka topic name",
            "name": "Select the Kafka topic",
            "properties": {
              "topic": {
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Topic Name",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "path",
                "labelHint": "Select the Kafka topic to send data to.",
                "order": "1",
                "required": true,
                "secret": false,
                "tags": [],
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:kafka-publish-action",
      "name": "Publish",
      "pattern": "To",
      "tags": [
        "dynamic"
      ]
    },
    {
      "actionType": "connector",
      "description": "Receive data from the Kafka topic that you select.",
      "descriptor": {
        "configuredProperties": {},
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "any"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Select the Kafka topic name",
            "name": "Select the Kafka topic",
            "properties": {
              "topic": {
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Topic Name",
                "group": "common",
                "javaType": "java.lang.String",
                "kind": "path",
                "labelHint": "Select the Kafka topic to receive data from.",
                "order": "1",
                "required": true,
                "secret": false,
                "tags": [],
                "type": "string"
              }
            }
          }
        ]
      },
      "id": "io.syndesis:kafka-subscribe-action",
      "name": "Subscribe",
      "pattern": "From",
      "tags": [
        "dynamic"
      ]
    }
  ],
  "componentScheme": "kafka",
  "configuredProperties": {},
  "dependencies": [
    {
      "id": "@project.groupId@:@project.artifactId@:@project.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Subscribe for and publish messages",
  "icon": "assets:kafka.svg",
  "id": "kafka",
  "name": "Kafka Message Broker",
  "properties": {
    "brokers": {
      "componentProperty": true,
      "deprecated": false,
      "displayName": "Kafka Broker URIs",
      "group": "common",
      "javaType": "java.lang.String",
      "kind": "property",
      "label": "common",
      "labelHint": "Comma separated list of Kafka broker URIs in the form host:port. Note that SSL URIs are not supported at this time and will cause an OOM at connection verification (see also https://issues.apache.org/jira/browse/KAFKA-4090)",
      "order": "1",
      "required": true,
      "secret": false,
      "type": "typeahead"
    }
  },
  "tags": [
    "verifier",
    "dynamic"
  ]
}

=== syndesisio/syndesis/app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
{
  "actions": [
    {
      "actionType": "connector",
      "description": "Start an integration from a Webhook",
      "descriptor": {
        "componentScheme": "servlet",
        "standardizedErrors": [
          {
            "name": "SERVER_ERROR",
            "displayName": "ServerError"
          }
        ],
        "configuredProperties": {
          "headerFilterStrategy": "syndesisHeaderStrategy",
          "httpMethodRestrict": "GET,POST"
        },
        "connectorCustomizers": [
          "io.syndesis.connector.webhook.WebhookConnectorCustomizer"
        ],
        "exceptionHandler": "io.syndesis.connector.webhook.WebhookOnExceptionHandler",
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "any"
        },
        "propertyDefinitionSteps": [
          {
            "description": "Webhook Configuration",
            "name": "configuration",
            "properties": {
              "contextPath": {
                "order": 0,
                "componentProperty": false,
                "deprecated": false,
                "description": "The Webhook token that will be set as final part of the URL",
                "displayName": "Webhook Token",
                "enum": [],
                "generator": "alphanum:50",
                "javaType": "String",
                "kind": "parameter",
                "required": true,
                "secret": false,
                "tags": [
                  "context-path"
                ],
                "type": "string"
              },
              "defaultResponse": {
                "order": 1,
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Default Response",
                "javaType": "String",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "legend"
              },
              "httpResponseCode": {
                "order": 2,
                "componentProperty": false,
                "deprecated": false,
                "description": "The return code to set in the HTTP response",
                "displayName": "Return Code",
                "javaType": "String",
                "kind": "parameter",
                "required": true,
                "secret": false,
                "type": "select",
                "enum": [{
                            "label": "200 OK",
                            "value": "200"
                        }, {
                            "label": "201 Created",
                            "value": "201"
                        }, {
                            "label": "202 Accepted",
                            "value": "202"
                        }, {
                            "label": "204 No Content",
                            "value": "204"
                        }]
              },
              "errorHandling": {
                "order": 3,
                "componentProperty": false,
                "deprecated": false,
                "displayName": "Error Handling",
                "javaType": "String",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "legend"
              },
              "returnBody": {
                "order": 4,
                "componentProperty": false,
                "defaultValue": true,
                "deprecated": false,
                "displayName": "Include error message in the return body",
                "javaType": "Boolean",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "boolean"
              },
              "errorResponseCodes": {
                "order": 5,
                "componentProperty": false,
                "defaultValue": "{}",
                "deprecated": false,
                "description": "The return code to set according to different error situations",
                "displayName": "Error Response Codes",
                "javaType": "Map",
                "kind": "parameter",
                "required": false,
                "secret": false,
                "type": "mapset",
                "extendedProperties": "{ \"mapsetValueDefinition\": {   \"enum\" : [{\"label\":\"400 Bad Request\",\"value\":\"400\"},{\"label\":\"404 Not Found\",\"value\":\"404\"},{\"label\":\"405 Method Not Allowed\",\"value\":\"405\"},{\"label\":\"409 Conflict\",\"value\":\"409\"},{\"label\":\"500 Server Error\",\"value\":\"500\"},{\"label\":\"501 Not Implemented\",\"value\":\"501\"},{\"label\":\"503 Service Unavailable\",\"value\":\"503\"}],    \"type\" : \"select\" },\"mapsetOptions\": {    \"i18nKeyColumnTitle\": \"When the error message is\",    \"i18nValueColumnTitle\": \"Return this HTTP response code\" }}"              }
            }
          }
        ]
      },
      "id": "io.syndesis:webhook-incoming",
      "metadata": {
        "serverBasePath": "/webhook"
      },
      "name": "Incoming Webhook",
      "pattern": "From",
      "tags": [
        "expose"
      ]
    }
  ],
  "dependencies": [
    {
      "id": "@project.groupId@:@project.artifactId@:@project.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Create direct connections with external systems through Webhooks",
  "icon": "assets:webhook.svg",
  "id": "webhook",
  "metadata": {
    "hide-from-connection-pages": true
  },
  "name": "Webhook"
}
