=== syndesisio/syndesis/app/connector/support/maven-plugin/src/main/resources/connector-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "actions": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "actionType": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "descriptor": {
              "type": "object",
              "properties": {
                "componentScheme": {
                  "type": "string"
                },
                "configuredProperties": {
                  "type": "object"
                },
                "connectorFactory": {
                  "type": "string"
                },
                "connectorCustomizers": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ],
                  "additionalProperties": false
                },
                "exceptionHandler": {
                  "type": "string"
                },
                "inputDataShape": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind"
                  ],
                  "additionalProperties": false
                },
                "outputDataShape": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind"
                  ],
                  "additionalProperties": false
                },
                "propertyDefinitionSteps": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "description": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "properties": {
                          "type": "object"
                        }
                      },
                      "required": [
                        "description",
                        "name",
                        "properties"
                      ],
                      "additionalProperties": false
                    }
                  ]
                },
                "standardizedErrors": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "displayName": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "displayName"
                      ],
                      "additionalProperties": false
                    }
                  ]
                }
              },
              "required": [
                "inputDataShape",
                "outputDataShape"
              ],
              "additionalProperties": false
            },
            "id": {
              "type": "string"
            },
            "metadata": {
              "type": "object"
            },
            "name": {
              "type": "string"
            },
            "pattern": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "actionType",
            "description",
            "descriptor",
            "id",
            "name",
            "pattern"
          ],
          "additionalProperties": false
        }
      ]
    },
    "componentScheme": {
      "type": "string"
    },
    "configuredProperties": {
      "type": "object"
    },
    "connectorCustomizers": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "connectorFactory": {
      "type": "string"
    },
    "dependencies": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "type"
          ],
          "additionalProperties": false
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "properties": {
      "type": "object"
    },
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "actions",
    "description",
    "icon",
    "id",
    "name"
  ],
  "additionalProperties": false
}

=== syndesisio/syndesis/app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
{
  "actions": [],
  "componentScheme": "rest-openapi",
  "configuredProperties": {
    "componentName": "connector-rest-swagger-http4"
  },
  "connectorCustomizers": [
    "io.syndesis.connector.rest.swagger.SpecificationResourceCustomizer",
    "io.syndesis.connector.rest.swagger.AuthenticationCustomizer",
    "io.syndesis.connector.rest.swagger.RequestCustomizer",
    "io.syndesis.connector.rest.swagger.ResponseCustomizer"
  ],
  "connectorFactory": "io.syndesis.connector.rest.swagger.ConnectorFactory",
  "dependencies": [
    {
      "id": "io.syndesis.connector:connector-rest-swagger:@project.version@",
      "type": "MAVEN"
    },
    {
      "id": "org.apache.camel:camel-http:@camel.version@",
      "type": "MAVEN"
    }
  ],
  "description": "Meta connector to generate swagger client connectors",
  "icon": "",
  "id": "rest-swagger",
  "metadata": {
    "hide-from-connection-pages": "true"
  },
  "name": "OpenAPI client",
  "properties": {
    "accessToken": {
      "description": "OAuth Access token",
      "displayName": "OAuth access token",
      "javaType": "java.lang.String",
      "order": 4,
      "secret": true,
      "type": "string"
    },
    "accessTokenExpiresAt": {
      "description": "Seconds in UTC when the access token expires",
      "javaType": "java.lang.Long",
      "type": "hidden"
    },
    "authenticationParameterName": {
      "description": "Name of the API key parameter",
      "displayName": "API key parameter name",
      "javaType": "java.lang.String",
      "order": 2,
      "required": true,
      "type": "hidden"
    },
    "authenticationParameterPlacement": {
      "displayName": "Placement of the API key parameter",
      "enum": [
        {
          "label": "header",
          "value": "header"
        },
        {
          "label": "query",
          "value": "query"
        }
      ],
      "javaType": "java.lang.String",
      "order": 4,
      "required": true,
      "type": "hidden"
    },
    "authenticationParameterValue": {
      "description": "Value of the API key authentication parameter",
      "displayName": "API key",
      "javaType": "java.lang.String",
      "order": 3,
      "required": true,
      "secret": true,
      "type": "string"
    },
    "authenticationType": {
      "displayName": "Authentication type",
      "enum": [
        {
          "label": "apiKey",
          "value": "apiKey"
        },
        {
          "label": "basic",
          "value": "basic"
        },
        {
          "label": "none",
          "value": "none"
        },
        {
          "label": "oauth2",
          "value": "oauth2"
        }
      ],
      "javaType": "java.lang.String",
      "order": 1,
      "type": "hidden"
    },
    "authorizationEndpoint": {
      "description": "URL for the start of the OAuth flow",
      "displayName": "OAuth Authorization Endpoint URL",
      "javaType": "java.lang.String",
      "order": 6,
      "required": true,
      "type": "string"
    },
    "authorizeUsingParameters": {
      "description": "Should the implementation send client id and client secret when performing OAuth flow",
      "javaType": "java.lang.String",
      "type": "hidden"
    },
    "basePath": {
      "description": "API basePath for example /v2. Default is unset if set overrides the value present in OpenAPI document.",
      "displayName": "Base path",
      "javaType": "java.lang.String",
      "order": 11,
      "type": "string"
    },
    "clientId": {
      "description": "OAuth Client ID, sometimes called Consumer Key",
      "displayName": "OAuth Client ID",
      "javaType": "java.lang.String",
      "order": 2,
      "type": "string"
    },
    "clientSecret": {
      "description": "OAuth Client Secret, sometimes called Consumer Secret",
      "displayName": "OAuth Client Secret",
      "javaType": "java.lang.String",
      "order": 3,
      "secret": true,
      "type": "string"
    },
    "host": {
      "description": "Scheme hostname and port to direct the HTTP requests to in the form of https://hostname:port.",
      "displayName": "Host",
      "javaType": "java.lang.String",
      "order": 10,
      "required": true,
      "type": "string"
    },
    "oauthScopes": {
      "description": "OAuth scopes needed for the API.",
      "displayName": "OAuth Scopes",
      "javaType": "java.lang.String",
      "order": 8,
      "type": "string"
    },
    "operationId": {
      "description": "ID of the operation from the OpenAPI document.",
      "displayName": "Operation ID",
      "javaType": "java.lang.String",
      "required": true,
      "type": "hidden"
    },
    "password": {
      "description": "Password to authenticate with.",
      "displayName": "Password",
      "javaType": "java.lang.String",
      "order": 3,
      "required": true,
      "secret": true,
      "type": "string"
    },
    "refreshToken": {
      "description": "OAuth Refresh token.",
      "displayName": "OAuth Refresh token",
      "javaType": "java.lang.String",
      "order": 5,
      "secret": true,
      "type": "string"
    },
    "refreshTokenRetryStatuses": {
      "description": "Comma separated list of HTTP statuses for which to refresh the OAuth access token using the refresh token.",
      "displayName": "HTTP statuses for refreshing OAuth token",
      "javaType": "java.lang.String",
      "type": "hidden"
    },
    "specification": {
      "description": "OpenAPI document defining the service.",
      "displayName": "Document",
      "javaType": "java.lang.String",
      "required": true,
      "type": "hidden"
    },
    "tokenEndpoint": {
      "description": "URL to fetch the OAuth Access token.",
      "displayName": "OAuth Token Endpoint URL",
      "javaType": "java.lang.String",
      "order": 7,
      "type": "string"
    },
    "tokenStrategy": {
      "displayName": "OAuth Token strategy",
      "javaType": "java.lang.String",
      "type": "hidden"
    },
    "username": {
      "description": "Username to authenticate with.",
      "displayName": "Username",
      "javaType": "java.lang.String",
      "order": 2,
      "required": true,
      "type": "string"
    }
  }
}

=== syndesisio/syndesis/app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
{
  "id": "sql",
  "name": "Database",
  "description": "Invoke SQL or stored procedures.",
  "icon": "fa-database",
  "dependencies": [
    {
      "type": "MAVEN",
      "id": "@project.groupId@:@project.artifactId@:@project.version@"
    }
  ],
  "configuredProperties": {},
  "tags": [
    "verifier"
  ],
  "properties": {
    "url": {
      "kind": "property",
      "displayName": "Connection URL",
      "group": "common",
      "label": "",
      "required": true,
      "type": "string",
      "javaType": "java.lang.String",
      "tags": [],
      "deprecated": false,
      "secret": true,
      "componentProperty": true,
      "defaultValue": "jdbc:postgresql://syndesis-db:5432/sampledb",
      "description": "JDBC URL of the database."
    },
    "user": {
      "kind": "property",
      "displayName": "Username",
      "group": "common",
      "label": "",
      "required": true,
      "type": "string",
      "javaType": "java.lang.String",
      "tags": [],
      "deprecated": false,
      "secret": true,
      "componentProperty": true,
      "defaultValue": "sampledb",
      "description": "Username for the database connection."
    },
    "password": {
      "kind": "property",
      "displayName": "Password",
      "group": "security",
      "label": "common,security",
      "required": false,
      "type": "string",
      "javaType": "java.lang.String",
      "tags": [],
      "deprecated": false,
      "secret": true,
      "componentProperty": true,
      "description": "Password for the database connection."
    },
    "schema": {
      "kind": "property",
      "displayName": "Schema",
      "group": "common",
      "label": "common",
      "required": false,
      "type": "string",
      "javaType": "java.lang.String",
      "tags": [],
      "deprecated": false,
      "secret": false,
      "componentProperty": true,
      "defaultValue": "sampledb",
      "description": "Database schema."
    }
  },
  "connectorCustomizers": [
    "io.syndesis.connector.sql.customizer.DataSourceCustomizer"
  ],
  "actions": [
    {
      "id": "sql-connector",
      "name": "Invoke SQL",
      "description": "Invoke SQL to obtain, store, update, or delete data.",
      "tags": [
        "dynamic"
      ],
      "pattern": "To",
      "actionType": "connector",
      "descriptor": {
        "componentScheme": "sql",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "json-schema"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "name": "SQL statement",
            "description": "Enter a SQL statement that starts with INSERT, SELECT, UPDATE or DELETE.",
            "properties": {
              "query": {
                "kind": "path",
                "displayName": "SQL statement",
                "group": "common",
                "required": true,
                "type": "string",
                "javaType": "java.lang.String",
                "deprecated": false,
                "secret": false,
                "description": "SQL statement to be executed. Can contain input parameters prefixed by ':#' (for example ':#MYPARAMNAME')."
              }
            }
          }
        ]
      }
    },
    {
      "id": "sql-start-connector",
      "name": "Periodic SQL invocation",
      "description": "Periodically invoke SQL to obtain, store, update, or delete data.",
      "tags": [
        "dynamic"
      ],
      "pattern": "From",
      "actionType": "connector",
      "descriptor": {
        "componentScheme": "sql",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStartConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "split": {
        },
        "propertyDefinitionSteps": [
          {
            "name": "SQL statement",
            "description": "Enter a SQL statement that starts with SELECT.",
            "properties": {
              "query": {
                "kind": "path",
                "displayName": "SQL statement",
                "group": "common",
                "required": true,
                "type": "string",
                "javaType": "java.lang.String",
                "deprecated": false,
                "secret": false,
                "description": "SQL SELECT statement to be executed."
              },
              "schedulerExpression": {
                "kind": "parameter",
                "displayName": "Period",
                "group": "consumer",
                "required": false,
                "type": "duration",
                "javaType": "long",
                "deprecated": false,
                "secret": false,
                "defaultValue": 1000,
                "description": "Delay in milliseconds between scheduling (executing)."
              }
            }
          }
        ]
      }
    },
    {
      "id": "sql-stored-connector",
      "name": "Invoke stored procedure",
      "description": "Periodically invoke a stored procedure.",
      "tags": [
        "dynamic"
      ],
      "pattern": "To",
      "actionType": "connector",
      "descriptor": {
        "componentScheme": "sql-stored",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStoredConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "json-schema"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "name": "Procedure name",
            "description": "Select the stored procedure.",
            "properties": {
              "procedureName": {
                "kind": "property",
                "group": "common",
                "displayName": "Procedure name",
                "required": false,
                "type": "string",
                "javaType": "java.lang.String",
                "tags": [],
                "deprecated": false,
                "secret": true,
                "componentProperty": true,
                "description": "Name of the stored procedure."
              },
              "template": {
                "kind": "path",
                "displayName": "Template",
                "group": "producer",
                "required": true,
                "type": "hidden",
                "javaType": "java.lang.String",
                "tags": [],
                "deprecated": false,
                "secret": false,
                "componentProperty": false,
                "defaultValue": "",
                "description": "Stored procedure template to perform."
              }
            }
          }
        ]
      }
    },
    {
      "id": "sql-stored-start-connector",
      "name": "Periodic stored procedure invocation",
      "description": "Periodically invoke a stored procedure.",
      "tags": [
        "dynamic"
      ],
      "pattern": "From",
      "actionType": "connector",
      "descriptor": {
        "componentScheme": "sql-stored",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStartStoredConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "name": "Procedure name",
            "description": "Select the stored procedure.",
            "properties": {
              "procedureName": {
                "kind": "path",
                "displayName": "Procedure name",
                "group": "producer",
                "required": true,
                "type": "string",
                "javaType": "java.lang.String",
                "tags": [],
                "deprecated": false,
                "secret": false,
                "componentProperty": true,
                "description": "Name of the stored procedure."
              },
              "template": {
                "kind": "path",
                "displayName": "Template",
                "group": "producer",
                "required": true,
                "type": "hidden",
                "javaType": "java.lang.String",
                "tags": [],
                "deprecated": false,
                "secret": false,
                "componentProperty": false,
                "defaultValue": "",
                "description": "Stored Procedure template to perform."
              },
              "schedulerExpression": {
                "kind": "parameter",
                "displayName": "Period",
                "group": "consumer",
                "required": false,
                "type": "duration",
                "javaType": "long",
                "deprecated": false,
                "secret": false,
                "defaultValue": 1000,
                "description": "Delay in milliseconds between scheduling (executing)."
              }
            }
          }
        ]
      }
    }
  ]
}

=== syndesisio/syndesis/app/connectors/connectors/dropbox-connector/src/main/resources/META-INF/syndesis/connector/dropbox.json
{
    "id": "dropbox",
    "name": "DropBox",
    "description": "File upload and download from Dropbox",
    "icon": "fa-dropbox",
    "dependencies": [
        {
            "type": "MAVEN",
            "id": "@project.groupId@:@project.artifactId@:@project.version@"
        }
    ],
    "componentScheme": "dropbox",
    "configuredProperties": {
        "tokenUrl": "https://api.dropboxapi.com/oauth2/token",
        "authorizationUrl": "https://www.dropbox.com/oauth2/authorize",
        "authenticationType": "oauth2"
    },
    "tags": [
        "verifier"
    ],
    "properties": {
        "accessToken": {
            "kind": "parameter",
            "displayName": "Access Token",
            "group": "common,security",
            "required": true,
            "type": "string",
            "javaType": "java.lang.String",
            "tags": [
                "oauth-access-token"
            ],
            "deprecated": false,
            "secret": true,
            "componentProperty": true,
            "description": "dropbox.com User Name"
        },
        "clientIdentifier": {
            "kind": "parameter",
            "displayName": "Client identifier",
            "group": "common,security",
            "required": true,
            "type": "string",
            "javaType": "java.lang.String",
            "tags": [
                "oauth-client-id"
            ],
            "deprecated": false,
            "secret": false,
            "componentProperty": true,
            "description": "Access Token"
        },
        "clientSecret": {
            "kind": "parameter",
            "displayName": "Client Secret",
            "group": "common,secret",
            "required": false,
            "type": "string",
            "javaType": "java.lang.String",
            "tags": [
                "oauth-client-secret"
            ],
            "deprecated": false,
            "secret": true,
            "componentProperty": true,
            "description": "Access Token"
        },
        "tokenUrl": {
            "kind": "property",
            "displayName": "Token URL",
            "group": "security",
            "label": "security",
            "required": false,
            "type": "string",
            "javaType": "java.lang.String",
            "tags": [
                "oauth-access-token-url"
            ],
            "deprecated": false,
            "secret": true,
            "componentProperty": true,
            "description": "The access token"
        },
        "authorizationUrl": {
            "kind": "property",
            "displayName": "Authorization URL",
            "group": "security",
            "label": "security",
            "required": false,
            "type": "string",
            "javaType": "java.lang.String",
            "tags": [
                "oauth-authorization-url"
            ],
            "deprecated": false,
            "secret": true,
            "componentProperty": true,
            "description": "Authorization URL"
        },
        "authenticationType": {
            "kind": "property",
            "displayName": "Authentication Type",
            "group": "security",
            "label": "security",
            "required": false,
            "type": "string",
            "javaType": "java.lang.String",
            "tags": [
                "authentication-type"
            ],
            "deprecated": false,
            "secret": true,
            "componentProperty": true,
            "description": "Authentication Type"
        }
    },
    "actions": [
        {
            "name": "upload",
            "description": "Upload a file to dropbox.com",
            "id": "io.syndesis:dropbox-upload-connector",
            "pattern": "To",
            "actionType": "connector",
            "descriptor": {
                "componentScheme": "dropbox",
                "inputDataShape": {
                    "kind": "any"
                },"outputDataShape":{"kind":"none"},
                "configuredProperties": {
                    "operation": "put"
                },
                "propertyDefinitionSteps": [
                    {
                        "name": "Upload to Drobbox",
                        "description": "Upload to Drobbox",
                        "properties": {
                            "uploadMode": {
                                "kind": "parameter",
                                "displayName": "Upload mode",
                                "group": "producer",
                                "required": true,
                                "type": "string",
                                "javaType": "java.lang.String",
                                "enum": [
                                    {
                                        "value": "add",
                                        "label": "Add"
                                    },
                                    {
                                        "value": "force",
                                        "label": "Force"
                                    }
                                ],
                                "deprecated": false,
                                "secret": false,
                                "description": "Upload mode"
                            },
                            "remotePath": {
                                "kind": "Remote path",
                                "displayName": "Remote path",
                                "group": "producer",
                                "required": false,
                                "type": "string",
                                "javaType": "java.lang.String",
                                "deprecated": false,
                                "secret": false,
                                "description": "Remote path"
                            }
                        }
                    }
                ]
            }
        },
        {
            "name": "download",
            "description": "Download from Dropbox",
            "id": "io.syndesis:dropbox-download-connector",
            "pattern": "From",
            "actionType": "connector",
            "descriptor": {
                "component-scheme": "dropbox",
                "inputDataShape": {
                    "kind": "none"
                },
                "outputDataShape": {
                    "kind": "any"
                },"configuredProperties":{"operation":"get"},
                "propertyDefinitionSteps": [
                    {
                        "name": "Download  from Dropbox",
                        "description": "Download  from Dropbox",
                        "properties": {
                            "remotePath": {
                                "kind": "parameter",
                                "displayName": "Folder of file name to download",
                                "group": "consumer",
                                "required": true,
                                "type": "string",
                                "javaType": "java.lang.String",
                                "deprecated": false,
                                "secret": false,
                                "description": "Folder of file name to download"
                            }
                        }
                    }
                ]
            }
        }
    ]
}
